openapi: 3.0.0
info:
  version: 1.0.0
  title: App Reviews Analyzer
  description: API for App Reviews Analyser

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /compute/scoreDistribution:
    get:
      description: Returns a bar chart as PNG image to show the review's score distribution between 2 period of time
      parameters:
        - name: date
          in: query
          description: Date to compare score distribution (if empty, no comparaison)
          schema:
            type: string
      responses:
        '200':
          description: Returns a bar chart as PNG image
          content:
            image/png:
              schema:
                type: string
                format: binary
  /compute/means:
    get:
      description: Returns a graphic as PNG image
      parameters:
        - name: timeDelta
          in: query
          description: Define the duration in days on which it computes cumulative results (default = 30)
          schema:
            type: integer
        - name: ignore
          in: query
          description: Indicates the number of first reviews to skip (default = 0)
          schema:
            type: integer
      responses:
        '200':
          description: Returns a graphic as PNG image
          content:
            image/png:
              schema:
                type: string
                format: binary
  /wordcloud/computeWords:
    get:
      description: Returns a 2 set of vocabulary and their frequencies 
      parameters:
        - name: alpha
          in: query
          description: Parameters to reduce noises in data
          schema:
            type: integer
        - name: n
          in: query
          description: Define the number of word per token vocabulary (group of consecutive word)
          schema:
            type: integer
        - name: lang
          in: query
          description: Language of analysed reviews from the following list ["de","en","es","fr","it","ja","pt","zh"]
          schema:
            type: string
        - name: score
          in: query
          description: Filter reviews on score (take all if empty or 0)
          schema:
            type: integer
        - name: start1
          in: query
          description: First period start date to compare
          schema:
            type: string
        - name: end1
          in: query
          description: First period end date to compare
          schema:
            type: string
        - name: start2
          in: query
          description: Second period start date to compare
          schema:
            type: string
        - name: end2
          in: query
          description: Second period end date to compare
          schema:
            type: string
      responses:
        '200':
          description: Returns a JSON object including the 2 set of vocabulary
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: array
                    items:
                      oneOf:
                      - type: string
                      - type: integer
  /wordcloud/generateImage:
    post:
      description: Returns a wordcloud as PNG image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
      responses:
        '200':
          description: Returns a graphic as PNG image
          content:
            image/png:
              schema:
                type: string
                format: binary

          